### ISSUE TITLE
You can't call return from within a Try::Tiny catch block

### ISSUE THREAD

**Issue by skington** [libwww-perl/libwww-perl#107]
As a result, calling LWP::UserAgent->simple_request with a malformed URL does *not* return a faked "that was a malformed URL" response, but proceeds to call $self->send_request instead.

I believe the problem was introduced [when eval was replaced by try/catch](https://github.com/libwww-perl/libwww-perl/commit/650853e6948aafad299d64714cfcaae169e9cf27#diff-e316f49c673f6e1c852d5b23a10e4b69R270). The problem is that [Try::Tiny does not support returning from the parent subroutine](https://github.com/p5sagit/Try-Tiny/blob/d8d64fc24d7b863f9b887d9e6eceacf52f2f9ea4/lib/Try/Tiny.pm#L229-L231) so the return statement is ignored.

**Comment by karenetheridge** [comment]
I'm a bit surprised we don't have a test for that error.. we should fix
that too :)

**Comment by genio** [comment]
@skington Oooh. We'll create a test and a fix as quickly as possible.  Thanks for pointing this out

**Comment by genio** [comment]
I think https://github.com/libwww-perl/libwww-perl/compare/genio/fixtry should accurately test for and fix the problem.

@skington Can you try that patch and ensure it works out the issue in your usage, please?

**Comment by skington** [comment]
Won't that also return a malformed request response if there's an error when sending, though?

**Comment by genio** [comment]
I think you're right.  Sorry about that, I think I'm moving too fast and not thinking enough. https://github.com/libwww-perl/libwww-perl/compare/genio/fixtry should be better now.

**Comment by skington** [comment]
That works for me, yes.

**Comment by oalders** [comment]
Closed via #108
