### ISSUE TITLE
[PATCH] Chainable methods in LWP::UserAgent [rt.cpan.org #73758]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/libwww-perl#163]
Migrated from [rt.cpan.org#73758](https://rt.cpan.org/Ticket/Display.html?id=73758) (status was 'new')

Requestors:
* dolmen@cpan.org

From dolmen@cpan.org on 2012-01-05 09:52:41:
```
This patch changes the methods in LWP::UserAgent that returned no useful
value. They now return $self. This allows to chain method calls.

Impacted methods: add_handler/set_my_handler/env_proxy/no_proxy.

Doc for those methods is updated to tell from which release this feature
is available.


Pull request: https://github.com/gisle/libwww-perl/pull/23


-- 
Olivier MenguÃ© - http://perlresume.org/DOLMEN
```

**Comment by genio** [comment]
https://github.com/libwww-perl/libwww-perl/pull/23

**Comment by genio** [comment]
@dolmen Since PR #23 was closed as the feature was down-voted, I'm going to close this issue out for now. If you'd like, please yell at me on the IRC channel and we can discuss it.
