### ISSUE TITLE
6.00 drops 5.6 support without apparent cause [rt.cpan.org #105982]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/libwww-perl#192]
Migrated from [rt.cpan.org#105982](https://rt.cpan.org/Ticket/Display.html?id=105982) (status was 'new')

Requestors:
* KENTNL@cpan.org

From kentnl@cpan.org on 2015-07-20 18:54:55:
```
LWP is in the dependency graph of a working CPAN::Reporter install.

Thus, getting a reporter working on 5.6 is a bit hard.

The previous release to 6.0 works, but subsequent ones bail due to $]<5.8

https://metacpan.org/diff/file?target=GAAS/libwww-perl-6.00/&source=OLEG/libwww-perl-5.837/#bin/lwp-mirror

I would request if it is at all possible, release this (apparent) superficial
limitation.
```

**Comment by genio** [comment]
Anything needing to decode unicode or use the Encode or utf8 modules in anyway can not work with 5.6. There is no real way to continue support for 5.6. If you're on 5.6, you'll need to use a pre-6.00 release.
