### ISSUE TITLE
t/apache.t does not respect proxy env variable [rt.cpan.org #119794]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/libwww-perl#204]
Migrated from [rt.cpan.org#119794](https://rt.cpan.org/Ticket/Display.html?id=119794) (status was 'new')

Requestors:
* todd.bruner@gmail.com

From todd.bruner@gmail.com on 2017-01-10 22:14:57:
```
t/apache.t hangs unable to reach www.apache.org

adding $ua->env_proxy
prior to line 14 seems to fix

------------------------------
todd.bruner@gmail.com
```

**Comment by genio** [comment]
As this is now an xt/author test, this is no longer a problem for userland.
