### ISSUE TITLE
LWP/Protocol/http.pm should use bytes [rt.cpan.org #63551]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/libwww-perl#221]
Migrated from [rt.cpan.org#63551](https://rt.cpan.org/Ticket/Display.html?id=63551) (status was 'open')

Requestors:
* asnyder@ariasystems.com

From asnyder@ariasystems.com on 2010-12-02 21:28:22:
```
http requests are calculating the wrong content length for utf8 strings.

adding "use bytes;" to LWP::Protocol::http::request fixes this problem.

perl 5.8.8 and later (tested on perl v5.10.1)

```

From gaas@cpan.org on 2010-12-02 21:56:55:
```
The "contract" is that the content of a HTTP::Message object should be bytes.

You are not supposed to be able to pass in a HTTP::Request where the content isn't 
representable as bytes.  What do you do to bypass these checks?


```

From asnyder@ariasystems.com on 2010-12-02 22:04:55:
```
On 12/02/2010 04:56 PM, Gisle_Aas via RT wrote:
> <URL: https://rt.cpan.org/Ticket/Display.html?id=63551>
>
> The "contract" is that the content of a HTTP::Message object should be bytes.
>
> You are not supposed to be able to pass in a HTTP::Request where the content isn't
> representable as bytes.  What do you do to bypass these checks?
>
>
>
>    
I send an XML request that happens to have multibyte characters.
```

**Comment by genio** [comment]
Considering that ```SOAP::Lite``` uses LWP as a backend, I can't imagine this is still a problem.  I'm going to close it out for now as there aren't any clear test cases and no test case I can come up with has issues.

As always, please yell at me and I'll reopen this if it turns out I'm wrong.

Thanks,
Chase
