### ISSUE TITLE
Test failures due to hash randomisation in perl 5.17.6 [rt.cpan.org #81381]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/libwww-perl#230]
Migrated from [rt.cpan.org#81381](https://rt.cpan.org/Ticket/Display.html?id=81381) (status was 'open')

Requestors:
* 'spro^^*%*^6ut#@&$%*c

From $_ = 'spro^^*%*^6ut#@&$>#!^!#&!pan.org'; y/a-z.@//cd; print on 2012-11-23 16:38:12:
```

```

From yves@cpan.org on 2012-11-27 21:35:32:
```
On Fri Nov 23 11:38:12 2012, SPROUT wrote:
> Perl 5.17.6 randomises hash seeds, exposing an existing bug in
> t/base/ua.t:
> 
> #    Expected: "http://example.com"
> #  base/ua.t line 101 is: ok($ua->proxy('http'),
> "http://example.com");
> # Test 34 got: "http://10.10.10.2:8080" (base/ua.t at line 105)
> #    Expected: "http://example.com"
> #  base/ua.t line 105 is: ok($ua->proxy('http'),
> "http://example.com");
> 
> I happen to have HTTP_PROXY set to http://10.10.10.2:8080 and
> http_proxy unset.
> 
> The test script sets http_proxy.  Which of HTTP_PROXY and http_proxy
> is picked up by sub
> LWP::UserAgent::env_proxy is going to be random, so the test will fail
> half the time.

I just pushed:

https://github.com/demerphq/libwww-
perl/commit/96791d2f72dc20ab6ff3c6ce6442a8db509bcfcc

and submitted a pull request:

https://github.com/gisle/libwww-perl/pull/3

to have it merged to 

https://github.com/gisle/libwww-perl

but i notice that itself is a fork of 

https://github.com/libwww-perl/libwww-perl

which has a lot of pull requests of its own:

https://github.com/libwww-perl/libwww-perl/pulls

So I am unclear if i pushed my request to the right place.

Anyway this is a major blocker for 5.18.

https://github.com/gisle/libwww-perl/pull/3
```

From $_ = 'spro^^*%*^6ut#@&$>#!^!#&!pan.org'; y/a-z.@//cd; print on 2012-11-27 21:51:41:
```

```

**Comment by genio** [comment]
@demerphq I don't think this issue still exists.  The [PR you submitted](https://github.com/gisle/libwww-perl/pull/3) was for the old repository and should likely be closed out.  I compared your changes against what's currently in LWP/UserAgent.pm and don't seem to see the same problems.

Can you test now and let us know if the problem still exists?

**Comment by demerphq** [comment]
If you guys have deterministic behaviour under hash randomisation then this
ticket can be closec

**Comment by genio** [comment]
@demerphq Thanks. I'll close out it out for now.  Please don't hesitate to yell at us if it turns out I'm wrong.
