### ISSUE TITLE
lwp-request: -e implies -s [rt.cpan.org #89783]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/libwww-perl#236]
Migrated from [rt.cpan.org#89783](https://rt.cpan.org/Ticket/Display.html?id=89783) (status was 'open')

Requestors:
* 'spro^^*%*^6ut#@&$%*c

From $_ = 'spro^^*%*^6ut#@&$>#!^!#&!pan.org'; y/a-z.@//cd; print on 2013-10-26 00:53:15:
```

```

From gaas@cpan.org on 2013-10-27 06:34:46:
```
The change was introduced in
https://github.com/libwww-perl/libwww-perl/commit/339432622042ee9e34670cae852047ee0b142196
about 3 years ago (in the 6.00 release).

I might not have noticed that there was a change in behaviour for -e in that
commit.

Since it's been that was for 3 years I don't think I want to change it back
now.

Do you think there is value in still having the old behaviour available
somehow?
```

From $_ = 'spro^^*%*^6ut#@&$>#!^!#&!pan.org'; y/a-z.@//cd; print on 2013-10-27 12:39:32:
```

```

From $_ = 'spro^^*%*^6ut#@&$>#!^!#&!pan.org'; y/a-z.@//cd; print on 2014-01-31 06:41:56:
```

```

**Comment by spazm** [comment]
@cpansprout 's comments didn't import from rt.  

> In version 5.834, I could dump the headers without the status code using -e.
> 
> In version 6.03, -e implies -s and there appears to be no way to turn it off.
> 
> I don’t know when the regression was introduced.

```
$ lwp-request5.10 -v 2>&1 | head -n 1
This is lwp-request version 5.834 (libwww-perl-5.837)
$ lwp-request5.10 -m GET  -e  'nntp://nntp.perl.org/000001ceab1a$29aebd20$7d0c3760$@cp.net' | head -n 3
Date: Fri, 6 Sep 2013 17:00:07 +0100
From: meta.support@cp.net ("John Unsworth - CP Meta Support")
Server: you can post

$ lwp-request5.12 -v 2>&1 | head -n 1
This is lwp-request version 6.03 (libwww-perl-6.03)
$ lwp-request5.12 -m GET  -e  'nntp://nntp.perl.org/000001ceab1a$29aebd20$7d0c3760$@cp.net' | head -n 3
200 OK
Date: Fri, 6 Sep 2013 17:00:07 +0100
From: meta.support@cp.net ("John Unsworth - CP Meta Support")
```

--

> Yes.  I can pipe it straight to MIME::Entity.  With the status line present, MIME::Entity treats a multi-part document as having a single part, because it doesn’t recognise the headers.
> 
> My development machine was upgraded a few months ago, and one of my scripts starting misbehaving.  I have only just figured out why.

--

> BTW, my solution here is to keep an old version of lwp-request around.  I don’t want to have to do that forever.

**Comment by spazm** [comment]
I was hoping there might be a handy mnemonic for an upcased anti-flag, but `-E` and `-S` are already used for other things.

Good to see that the documentation is updated to show that `-e` implies `-s`

```
     -s            Display response status code
    -S            Display response status chain (implies -u)
    -e            Display response headers (implies -s)
    -E            Display whole chain of headers (implies -S and -U)
```

for OP's original use case, they could pipe through `tail -n +2` or similar to skip the first line before piping to MIME::Entity.  Not pretty, but probably easier than keeping an old version of lwp around?

```
root@4c4e7c1a5222:/libwww-perl# lwp-request -v 2>&1 | head -n 1
This is lwp-request version 6.31 (libwww-perl-6.31)
root@4c4e7c1a5222:/libwww-perl# lwp-request -m GET -s -e 'nntp://nntp.perl.org/000001ceab1a$29aebd20$7d0c3760$@cp.net' | tail -n +2 | head -n 3
Date: Fri, 6 Sep 2013 17:00:07 +0100
From: meta.support@cp.net ("John Unsworth - CP Meta Support")
Server: you can post
```

#cpan-prc :)

**Comment by oalders** [comment]
@spazm thanks for helping to work through these issues.  It's much appreciated.  :)  If you have the inclination to review any of the outstanding pull requests, there's a bunch that need some love.  We could probably merge some of the existing PRs if someone is able to take a close look at verify that they're ok to apply.

**Comment by oalders** [comment]
Also, this seems like a workable solution, if not ideal for the OP.  I'll close for now.  We can re-open if anyone would like to revisit this.
