### ISSUE TITLE
LWP::UserAgent: Bad http proxy specification 'http://[IPv6]...'  [patch] [rt.cpan.org #94654]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/libwww-perl#237]
Migrated from [rt.cpan.org#94654](https://rt.cpan.org/Ticket/Display.html?id=94654) (status was 'open')

Requestors:
* dam@cpan.org

Attachments:
* [ipv6-http-proxy.patch](https://rt.cpan.org/Ticket/Attachment/1349647/716199/ipv6-http-proxy.patch)
* [libwww-perl-6.19-Accept-proxy-URLs-with-IPv6-host-names.patch](https://rt.cpan.org/Ticket/Attachment/1705420/916173/libwww-perl-6.19-Accept-proxy-URLs-with-IPv6-host-names.patch)

From dam@cpan.org on 2014-04-11 20:57:06:
```
Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=714961:

Package: libwww-perl
Version: 6.04-1
Tags: ipv6, patch

	The current version of LWP::UserAgent apparently dislikes IPv6
	addresses given for proxies.  Consider, e. g.:

$ http_proxy=http://\[2001:db8::1\]:3128/ perl -e '
      use strict;
      use warnings;
      require LWP::UserAgent;

      my $ua = LWP::UserAgent->new ();
      $ua->env_proxy ();

      my $r = $ua->get ("http://www.example.org/");
      warn ($r->status_line ());
      die () unless ($r->is_success ());' 
Bad http proxy specification 'http://[2001:db8::1]:3128/' at -e line 1
$ 

	The patch hereby suggested turns it into:

200 OK at -e line 1.

	(provided that an IPv6 address of an active HTTP proxy is
	given.)

	TIA.
```

From ppisar@redhat.com on 2017-02-16 13:11:33:
```
Dne PÃ¡ 11.dub.2014 16:57:06, DAM napsal(a):
> 	The current version of LWP::UserAgent apparently dislikes IPv6
> 	addresses given for proxies.  Consider, e. g.:
> 
Just a nit pick: It's better to use non-possessive capturing group.
```

**Comment by alessiotomelleri** [comment]
Hi,

I'm facing with issue reported in  [https://aur.archlinux.org/packages/perl-http-proxy/](here)
(see the comment)

Is it possible apply the ipv6 patch ? 

thx in advance
Alessio Tomelleri

**Comment by genio** [comment]
Hi Everyone,

A new release has been cut and this is now hopefully corrected!  Please let us know if it's otherwise.

-- Chase
