### ISSUE TITLE
problems with lwp-download --help 

### ISSUE THREAD

**Issue by xenu** [libwww-perl/libwww-perl#262]
```
[04:10] c:\Users\xenu> lwp-download --help
C:\Strawberry\perl\bin\lwp-download version [unknown] calling Getopt::Std::getopts (version 1.12 [paranoid]),
running under Perl version 5.26.0.

Usage: lwp-download [-OPTIONS [-MORE_OPTIONS]] [--] [PROGRAM_ARG1 ...]

The following single-character options are accepted:
        Boolean (without arguments): -a -s

Options may be merged together.  -- stops processing of options.

For more details run
        perldoc -F C:\Strawberry\perl\bin\lwp-download
  [Now continuing due to backward compatibility and excessive paranoia.
   See 'perldoc Getopt::Std' about $Getopt::Std::STANDARD_HELP_VERSION.]
Usage: lwp-download [-a] <url> [<lpath>]
```

Obviously setting `$Getopt::Std::STANDARD_HELP_VERSION` would fix the warning. However, the real problem is the fact that usage information is autogenerated and isn't very helpful. 

My idea is to put full usage information in SYNOPSIS section of `lwp-download` POD, migrate to `Getopt::Long` and enable its `auto_help` option.

If you agree with that, I can prepare a PR with above changes.

**Comment by genio** [comment]
I'd be happy to see that done.

**Comment by oalders** [comment]
Seems fine to me as well.  It does introduce one more dependency, though.

**Comment by genio** [comment]
Getopt::Long and Getopt::Std are core modules as of Perl 5. So, that shouldn't be a concern.

**Comment by oalders** [comment]
I did not know that.  :)  Sounds good then!

**Comment by xenu** [comment]
Note that LWP is already using Getopt::Long in `Makefile.PL`, `lwp-dump` and `lwp-request`.
