### ISSUE TITLE
Wishlist: option to turn off sending TE header

### ISSUE THREAD

**Issue by perlancar** [libwww-perl/libwww-perl#27]
Since a few weeks ago, my internet banking module Finance::Bank::ID::BCA fails with Connection Reset error when it tries to connect to https://ibank.klikbca.com/ . The module uses WWW::Mechanize, which in turns uses LWP::UserAgent.

A closer look reveals that the server is now rejecting TE request header. It would be nice if LWP::Protocol::http lets us customize whether to send the header or not.

FYI, the server also rejects HTTP/1.0 protocol.

Thanks.

Ref: http://www.perlmonks.org/?node_id=957926

**Comment by y** [comment]
> There is already an ugly interface for this; ```push(@LWP::Prococol::http::EXTRA_SOCK_OPTS, SendTE => 0)```

I tried this, and it doesn't work for me. Still getting TE header and Connection: TE, close.
Tried with Perls 5.8.9 .. 5.24 and LWPs 5.837 .. 6.15

**Comment by genio** [comment]
@preaction Your proposal looks pretty good at a first glance.  Would you mind submitting it as a PR so we could review and hopefully close this issue out?

**Comment by preaction** [comment]
... I was wondering if this would ever get merged, and it turns out I never made a PR so no wonder... I've also rebased this so it should be easier to merge.
