### ISSUE TITLE
LWP::UserAgent Documentation is not clear: timeout is given a 500 error

### ISSUE THREAD

**Issue by perllaghu** [libwww-perl/libwww-perl#277]
It took me a while to find it in the code, a `$response` object will have a `$response->code` value of 500 if the connection times out (as well as if the server responds with a genuine _internal server error_

It would be nice to have that more explicit somewhere.

Thankee.

**Comment by skaji** [comment]
LWP::UserAgent's documentation says:

>  Error responses that LWP generates internally will have the "Client-Warning" header set to the value "Internal response". If you need to differentiate these internal responses from responses that a remote server actually generates, you need to test this header value.
