### ISSUE TITLE
New LWP breaks MSOUTH/ParallelUserAgent-2.62

### ISSUE THREAD

**Issue by eserte** [libwww-perl/libwww-perl#280]
ParallelUserAgent's test suite started to fail:
```
local/compatibility.t .. 
Failed 1/20 subtests 
local/file.t ........... ok
Oops: Answer (0) for 'http://127.0.0.1:11123/page1' was 
        500: Can't call method "send_te" on unblessed reference at /home/cpansand/.cpan/build/2018022421/libwww-perl-6.32-0/blib/lib/LWP/Protocol/http.pm line 34, <DAEMON> line 1.
 ""
local/http.t ........... 
Failed 8/15 subtests 
local/timeouts.t ....... 
Failed 21/25 subtests 
```
This is very likely due to this change in LWP: https://metacpan.org/source/OALDERS/libwww-perl-6.32/Changes#L5

I think there are two possibilities:
* ParallelUserAgent has to adapt
* Accessing the send_te member in https://metacpan.org/source/OALDERS/libwww-perl-6.32/lib/LWP/Protocol/http.pm#L33 should not be done with a method call, but using hash access. This might sound ugly, but the other two `$self->{ua}` accesses in this function were done just like this, so it would be consistent.

**Comment by eserte** [comment]
I also opened https://rt.cpan.org/Ticket/Display.html?id=124564

**Comment by eserte** [comment]
Another affected module: DOUGDUDE/Test-Override-UserAgent-0.004001.tar.gz
```
#   Failed test 'Live request went through in scope install'
#   at t/live_restriction.t line 92.
#          got: '500 Can't call method "send_te" on unblessed reference'
#     expected: '200 OK'
# Looks like you failed 1 test of 9.
t/live_restriction.t ............. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/9 subtests 
```

**Comment by oalders** [comment]
Thanks @eserte. @preaction thoughts on this?

**Comment by preaction** [comment]
I think when I had initially sent this patch, the other lines used method accessors to get those values. Since that is no longer the case, I think the correct solution is to change my line to a hash accessor like the other two were changed. I'll prep a PR quick.

**Comment by preaction** [comment]
I was wrong: This code has always used hash accessors back to when it was originally written (one line in 2009, the other in 2013). So, now the line I added does as well.

**Comment by oalders** [comment]
New release has been uploaded.
