### ISSUE TITLE
Timeouts with 1024 byte packet sizes

### ISSUE THREAD

**Issue by targzeta** [libwww-perl/libwww-perl#305]
Hi,
due the fix introduced in Net::HTTP 6.10-DEV (Fix RT#112313 - Hang in my_readline() when keep-alive => 1 and $response_size % 1024 == 0), could not this be forced into the cpanfile?

I have had a very difficult timeout problem.

Thank you in advance,
Emanuele

**Comment by targzeta** [comment]
Hi Olaf,
thank you for your quickly reply!

We had some random connection timeout with our server. Investigating the problem I have noticed that in that cases the server replied with a packet of 1024 bytes. So I lended on  [this pull request](https://github.com/libwww-perl/Net-HTTP/pull/15) for Net::HTTP.

Starman:
```
$> cat foo.psgi
sub { [ 200, [], [ "x" x 904 ] ] }

$> starman --keepalive-timeout 20 foo.psgi
```

Test script with Net::HTTP 6.09 (500 read timeout after 10 seconds):
```
$> time /opt/perl/bin/perl -MNet::HTTP -MLWP::UserAgent -e 'print "Net::HTTP: $Net::HTTP::VERSION\nLWP::UserAgent: $LWP::UserAgent::VERSION\n"; print LWP::UserAgent->new(keep_alive => 1, timeout => 10)->post(q(http://127.0.0.1:5000))->status_line'
Net::HTTP: 6.09
LWP::UserAgent: 6.36
500 read timeout
real    0m10.159s
user    0m0.127s
sys     0m0.020s
```
![test_http_6 09](https://user-images.githubusercontent.com/2431105/50959068-64de1e00-14c2-11e9-935c-f090e91e2888.jpg)

Test with Net::HTTP 6.18 (200 OK):
```
$> time /opt/perl/bin/perl -MNet::HTTP -MLWP::UserAgent -e 'print "Net::HTTP: $Net::HTTP::VERSION\nLWP::UserAgent: $LWP::UserAgent::VERSION\n"; print LWP::UserAgent->new(keep_alive => 1, timeout => 10)->post(q(http://127.0.0.1:5000))->status_line'
Net::HTTP: 6.18
LWP::UserAgent: 6.36
200 OK
real    0m0.152s
user    0m0.130s
sys     0m0.021s
```
![test_http_6 18](https://user-images.githubusercontent.com/2431105/50959072-67d90e80-14c2-11e9-99ec-5852a1b8a2c8.jpg)

[This zip](https://github.com/libwww-perl/libwww-perl/files/2744606/test.zip) contains also the pcap files.

As you can see, the server in both cases replies with 200 OK, but the UserAgent returns 500 timeout when we have Net::HTTP 6.09.

Best regards,
Emanuele

**Comment by oalders** [comment]
Hi Emanuele,

Thanks very much for this -- it's very helpful. I'm a bit confused, though.  Will upgrading to Net::HTTP 6.18 not solve the problem?

All the best,

Olaf

**Comment by oalders** [comment]
Ah, right.  Yes, that makes sense. We should do this.  I can put something together.

Best,

Olaf
