### ISSUE TITLE
INSTALL file gives incorrect instructions

### ISSUE THREAD

**Issue by haarg** [libwww-perl/libwww-perl#316]
The INSTALL file has instructions referencing the module libwww::perl, which doesn't exist.

**Comment by genio** [comment]
Given that this is one of those special dists with a name that doesn't really match a module, should we remove the `[InstallGuide]` dzil section and create a still copy of the INSTALL file to just keep in the repo itself and manually make the appropriate edits?

**Comment by oalders** [comment]
Adding `main_module` to `dist.ini` doesn't seem to help.  Not sure where `$zilla->name` gets its source from.  https://metacpan.org/release/Dist-Zilla-Plugin-InstallGuide/source/lib/Dist/Zilla/Plugin/InstallGuide.pm#L204

**Comment by karenetheridge** [comment]
I'll fix that in ::InstallGuide.
