### ISSUE TITLE
SSL site read timeout

### ISSUE THREAD

**Issue by ribugent** [libwww-perl/libwww-perl#323]
Hello I found an issue when I try to access to an ssl site

```shell
$ lwp-request -t 10 -esS https://www.miamiherald.com/living/advice/
GET https://www.miamiherald.com/living/advice/
500 read timeout
Content-Type: text/plain
Client-Date: Tue, 10 Sep 2019 11:55:16 GMT
Client-Warning: Internal response

read timeout at /opt/plenv/versions/5.14.2/lib/perl5/site_perl/5.14.2/Net/HTTP/Methods.pm line 266.
```

I'm using 6.39 release.

Could you take a look?

Thank you!

**Comment by skaji** [comment]
Why do you think it is an lwp issue?

**Comment by lifeboatpres** [comment]
I tried on CentOS 6, 7, and 8 and couldn't get `wget`, `curl`, or `Furl` to work for this URL. I could only get this URL to work with puppeteer and Windows. I need some solution that works on Linux. I could use a different version of Linux if I knew that would work.

**Comment by oalders** [comment]
I wonder if there's some filtering of user agent names.  Any more success if you change the name of the agent?  https://metacpan.org/pod/LWP::UserAgent#agent

**Comment by lifeboatpres** [comment]
"I wonder if there's some filtering of user agent names." I automatically change the user agent name to a standard one. https://www.miamiherald.com is the only URL on the planet that is giving me trouble like this. I also tried different IPs.

**Comment by oalders** [comment]
In that case I think this might be better dealt with as a StackOverflow question.

**Comment by oalders** [comment]
Closing for now.  We can re-open this ticket if there some evidence that this is a bug in `libwww-perl`.
