### ISSUE TITLE
LWP::Simple - Can't Connect to Non Standard Port

### ISSUE THREAD

**Issue by LeeThompson** [libwww-perl/libwww-perl#345]
```
use LWP::Simple;
use strict;

my $url = "http://localhost:8080/sabnzbd/api?mode=version&apikey=REDACTED";
my $http_response = getprint($url);
```

`500 Can't connect to localhost:8080 (Bad address)`

Curl works:

`curl http://localhost:8080/sabnzbd/api?mode=version&apikey=REDACTED`
`2.3.9`

**Comment by skaji** [comment]
* Use LWP::UserAgent instead and check the response object in detail.
* How do you run the server "localhost:8080"?
* Which OS do you use? What are the version of perl, LWP, Net:HTTP, IO::Socket::INET and IO::Socket::IP?

**Comment by LeeThompson** [comment]
The host software is SABNZBd (https://sabnzbd.org/wiki/advanced/api) this is interfacing with it's API (I am currently using batch and curl as a workaround).

Software:

- Windows 10 Professional (2004) (19041.329)
- Perl v5.30.2 (x64 Strawberry Perl)
- SABNZBd 2.3.9 (host software where I'm trying to have Perl interact with the API)


Result with LWP::UserAgent (data Dumper follows the initial error)

```
Can't connect to localhost:8080 (Bad address)

Bad address at C:/Perl/perl/site/lib/LWP/Protocol/http.pm line 50.
$VAR1 = bless( {
                 '_rc' => 500,
                 '_msg' => 'Can\'t connect to localhost:8080 (Bad address)',
                 '_request' => bless( {
                                        '_method' => 'GET',
                                        '_content' => '',
                                        '_headers' => bless( {
                                                               'user-agent' => 'libwww-perl/6.46'
                                                             }, 'HTTP::Headers' ),
                                        '_uri' => bless( do{\(my $o = 'http://localhost:8080/sabnzbd/api?mode=version&apikey=REDACTED')}, 'URI::http' )
                                      }, 'HTTP::Request' ),
                 '_headers' => bless( {
                                        '::std_case' => {
                                                          'client-date' => 'Client-Date',
                                                          'client-warning' => 'Client-Warning'
                                                        },
                                        'client-date' => 'Sat, 27 Jun 2020 23:26:28 GMT',
                                        'content-type' => 'text/plain',
                                        'client-warning' => 'Internal response'
                                      }, 'HTTP::Headers' ),
                 '_content' => 'Can\'t connect to localhost:8080 (Bad address)

Bad address at C:/Perl/perl/site/lib/LWP/Protocol/http.pm line 50.
'
               }, 'HTTP::Response' );
```

**Comment by skaji** [comment]
* What are the versions of perl, LWP, Net::HTTP, IO::Socket::INET and IO::Socket::IP?
* How about `http://127.0.0.1:8080` and `http://[::1]:8080` ?

**Comment by LeeThompson** [comment]
That's interesting, IP address worked.   (DNS is fine on the machine so not sure what's up with that.)

**Comment by skaji** [comment]
LWP delegates socket creation to IO::Socket::IP.

I suspect the following script fails in your environment.

```perl
#!/usr/bin/env perl
use strict;
use warnings;
use IO::Socket::IP;

my $socket = IO::Socket::IP->new(
    PeerAddr => "localhost",
    PeerPort => "8080",
    Proto => "tcp",
) or die "connect: $!";

warn "connect OK\n";

```

If it actually fails and you think it should succeed, then you may create a ticket against IO::Socket::IP.

**Comment by LeeThompson** [comment]
I think I figured out the issue, Hyper-V is present and for whatever reason Socket was returning the IP address of the private adapter rather than the actual adapter.

**Comment by jtconsol** [comment]
For posterity: Just had a similar problem that made me stumble upon this issue - A local webapp is running fine in the browser at `http://localhost:3000`, but a perl script can't access that same URL: `Can't connect to localhost:3000 (Bad address)` on Windows 10. After a while I remembered [I had a similar issue a while ago](https://stackoverflow.com/a/40000255/1529709). The problem turned to be `localhost` resolving to both the IPv6 and IPv4 interfaces - and the target app was only running on the IPv4 one :) 

Using the IPv4 address obviously solves this problem. Another way to resolve it is to provide LWP with default socket options:

```
use IO::Socket::IP;  # needed for "AF_INET"
@LWP::Protocol::http::EXTRA_SOCK_OPTS = ( Family => AF_INET );

```
