### ISSUE TITLE
ActivePerl 5.14 & LWP 6.44+ & Windows 10: fails to connect with "Bad file descriptor"

### ISSUE THREAD

**Issue by michaelherger** [libwww-perl/libwww-perl#348]
Here's an odd one I am having a hard time with to understand. It doesn't make sense to me. Yet here it is, and I hope somebody is able to point me at what obvious thing I'm missing...

We have an [application](http://github.com/Logitech/slimserver) for which we're still using ActivePerl 5.14 on Windows due to the many dependencies, and the packagers we are using (ActiveState's PerlApp etc.).

A few months ago [I updated the more than a decade old LWP version we had been using for many years to v6.44](https://github.com/Logitech/slimserver/commit/b4e384c78954062b23bffa24703a270cab71d0de). I decided to use the source, rather than a package from ActiveState, as that's stuck on 6.02. This works fine on most platforms (in addition to Windows we support macOS and many flavours of Linux). And it did work just fine on Windows until a few days ago. 

A few days ago we started seeing the "Bad file descriptor" issue. At first I thought it was due to one of the server's update and enforcing TLS v1.2 or later. Alas, I see the same error with plain text http using the following simple test script:

```perl
use LWP::UserAgent;

print "$LWP::UserAgent::VERSION\n";

my $ua = LWP::UserAgent->new();
my $response = $ua->get('http://repos.squeezecommunity.org/extensions.xml');

print $response->status_line;

1;
```

Result with v6.44:
```
> perl5.14.1.exe -I. test.pl
6.44
500 write failed: Bad file descriptor
```

After reverting the LWP update, the script would work:
```
> perl5.14.1.exe -I. test.pl
2.033
200 OK
```

I manually updated to 6.46, too, without success.

So here I am, absolutely clueless. Any ideas?

**Comment by oalders** [comment]
It would probably helpful if we could pin this down to the exact version where things break. I realize that may be quite tedious for you to do, but that would be a good starting point.

**Comment by michaelherger** [comment]
What would be the easiest to to get working copies out of GitHub? I understand that at some point the module was split up into multiple independent repositories/modules. I guess I'd have to keep them in sync somehow? What is the bare minimum of modules I'd need to do a simple http request like in my example?

**Comment by oalders** [comment]
You could install the modules locally:

`cpm install --cpanfile cpanfile`

That will install them to `./local`.

Then you can use `local::lib` when running your script:

`perl -Mlocal::lib=local test.pl`

I think this should work on Windows. You'd need https://metacpan.org/pod/App::cpm to start with and possible `cpm install -g local::lib` as well.

**Comment by michaelherger** [comment]
Ok, here's a first quick test, checking out tagged commits. Breaking change seems to be in 6.05:

```
$ git checkout 6.04
Previous HEAD position was b1921799... Release 6.05
HEAD is now at 4a4ed7bc... Release 6.04

$ perl5.14.1.exe -I. test.pl
6.04
200 OK

$ git checkout 6.05
Previous HEAD position was 4a4ed7bc... Release 6.04
HEAD is now at b1921799... Release 6.05

$ perl5.14.1.exe -I. test.pl
6.05
500 Status read failed: A non-blocking socket operation could not be completed immediately.
```

**Comment by michaelherger** [comment]
Ok, I believe sanity is restored: my test case would fail, but the application would not (or not in the way described). As I mentioned we package the application using PerlApp. Which means it's self contained, comes with its own copies of all modules. My test I run on a system with Perl installed. It then picked up some files from the Perl installation, some from the application's collection of included dependencies. The included copies would fit together, the pre-installed `Net::HTTP` was older, thus the conflict.

I'm sorry for the noise. And thanks for the hint about how to test this.

**Comment by oalders** [comment]
I'm happy to hear that you got to the bottom of this. Thanks for sharing your process and the outcome.
