### ISSUE TITLE
Redirect tests fail in environment with web gateway

### ISSUE THREAD

**Issue by svonohr** [libwww-perl/libwww-perl#350]
The tests in `t/redirect.t` introduced in issue #171 fail when run from our company network. This seems to be because the web gateway immediatly acceps connections on the used test IP `198.51.100.123`. So the `$res->content` result actually contains a read timeout. While this is an issue with the web gateway, I think this could affect other users aswell and it might not be easily fixable in the gateway. Instead it might be simpler to modify the test to handle this special environment. Imho the exact `$res->content` result does not matter for the test.

The exact test output is:
```
#   Failed test '... and has tells us about the problem'
#   at t/redirect.t line 20.
#                   'read timeout at /usr/local/share/perl/5.22.1/Net/HTTP/Methods.pm line 268.
# '
#     doesn't match '(?^i:Can't connect)'
#   Failed test '... and has tells us about the problem'
#   at t/redirect.t line 36.
#                   'read timeout at /usr/local/share/perl/5.22.1/Net/HTTP/Methods.pm line 268.
# '
#     doesn't match '(?^i:Can't connect)'
```

**Comment by karenetheridge** [comment]
One way of solving this is to use Test::RequiresInternet in the test, which would respect $NO_NETWORK_TESTING being set in the environment -- and then users with interesting network configurations can set NO_NETWORK_TESTING=1 when installing. (We should be respecting this variable, regardless, in all our tests that make live network connections.)

**Comment by oalders** [comment]
Ping @simbabque, just out of interest. I think we had discussed which IP to use a little bit before we merged that.

**Comment by svonohr** [comment]
I think the IP choosen for this test is fine. It's in a reserved range so there shouldn't be anything running on this IP. Unfortunatly this doesn't seem to be the case for the web gateway. I'm fine with having an environment variable to disable tests involving the network.

**Comment by vanHoesel** [comment]
well painted out @karenetheridge , that is indeed the correct way of dealing with it
