### ISSUE TITLE
prereqs need adjusting

### ISSUE THREAD

**Issue by karenetheridge** [libwww-perl/libwww-perl#353]
This is just a warning, but is causing some alarm in the wild: https://rt.cpan.org/Ticket/Display.html?id=133608

**Comment by oalders** [comment]
What exactly is the problem here?

**Comment by bekuno** [comment]
Please see at https://metacpan.org/source/OALDERS/libwww-perl-6.49/Makefile.PL:
 
    # inserted by Dist::Zilla::Plugin::DynamicPrereqs 0.037
    sub _add_prereq {
      my ($mm_key, $module, $version_or_range) = @_;
      $version_or_range ||= 0;
      warn "$module already exists in $mm_key (at version $WriteMakefileArgs{$mm_key}{$module}) -- need to do a sane metamerge!"
        if exists $WriteMakefileArgs{$mm_key}{$module}
          and $WriteMakefileArgs{$mm_key}{$module} ne '0'
          and $WriteMakefileArgs{$mm_key}{$module} ne $version_or_range;
      warn "$module already exists in FallbackPrereqs (at version $FallbackPrereqs{$mm_key}{$module}) -- need to do a sane metamerge!"
        if exists $FallbackPrereqs{$module} and $FallbackPrereqs{$module} ne '0'
            and $FallbackPrereqs{$module} ne $version_or_range;
      $WriteMakefileArgs{$mm_key}{$module} = $FallbackPrereqs{$module} = $version_or_range;
      return;
    }
 
This leads to this result when installing:
 
    HTTP::Status already exists in PREREQ_PM (at version 6.07) -- need to do a sane metamerge! at Makefile.PL line 159.
    Use of uninitialized value in concatenation (.) or string at Makefile.PL line 162.
    HTTP::Status already exists in FallbackPrereqs (at version ) -- need to do a sane metamerge! at Makefile.PL line 162.
    HTTP::Status already exists in PREREQ_PM (at version 6.07) -- need to do a sane metamerge! at Makefile.PL line 159.
    Use of uninitialized value in concatenation (.) or string at Makefile.PL line 162.
    HTTP::Status already exists in FallbackPrereqs (at version ) -- need to do a sane metamerge! at Makefile.PL line 162.

The problem is in line 160.
          warn "$module already exists in FallbackPrereqs (at version $FallbackPrereqs{$mm_key}{$module}) -- need to do a sane metamerge!"
I think that his should be
      warn "$module already exists in FallbackPrereqs (at version $FallbackPrereqs{$module}) -- need to do a sane metamerge!"

**Comment by karenetheridge** [comment]
The only issue in libwww-perl is that two different things are supplying a prereq version for HTTP::Status. It's just a warning, and not a problem in this case as 6.07 is always greater than 0, but could cause some confusion on the user end.

I'll take a look at the code tonight to see if we can declare prereqs more clearly (I think we might be able to remove the dynamic prereq entirely now).

**Comment by simbabque** [comment]
We're not using Dist::Zilla::Plugin::DynamicPrereqs any more. It was dropped in e30cb443711e78b8995808712fe7e44fbec6768c to fix this issue.
