### ISSUE TITLE
request: support for gemini protocol

### ISSUE THREAD

**Issue by guzzisti** [libwww-perl/libwww-perl#354]
> Gemini is a new, collaboratively designed internet protocol, which explores the space inbetween gopher and the web, striving to address (perceived) limitations of one while avoiding the (undeniable) pitfalls of the other.

Ressources (including spec):
https://gemini.circumlunar.space/
gemini://gemini.circumlunar.space

As LWP supports gopher and http(s), i think its appropiate to have gemini support as well.

**Comment by genio** [comment]
I think this protocol should likely be created as its own module, LWP::Protocol::gemini

Just like LWP::Protocol::https, releasing outside of the libwww-perl module allows the protocol implementation to be updated/fixed without the need to wait on the libwww-perl dist.
