### ISSUE TITLE
LWP::UserAgent with proxy issues entire hostname in request [rt.cpan.org #65600]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/libwww-perl#360]
Migrated from [rt.cpan.org#65600](https://rt.cpan.org/Ticket/Display.html?id=65600) (status was 'new')

Requestors:
* tom@ritter.vg

From https://www.google.com/accounts/o8/id?id=AItOawm6xJ02QeyEObA0yWFi-nPqIB-r-ZS6_sg on 2011-02-09 21:32:04
:
```
When communicating via SSL using a proxy, requests are issued of the form:
  GET https://example.com/ HTTP/1.1
Rather than:
  GET / HTTP/1.1

Requests made without SSL, or using a proxy over HTTP, are made with only /.  This happens whether or not the env_proxy method is 
used.

I tested using Burp proxy http://www.portswigger.net/burp/proxy.html, it shows the requests coming into the proxy with the entire 
hostname, and the server shows the request leaving the proxy (untampered) doing the same.

Below is a script that can demonstrate 6 combinations:

          No Proxy | Proxy | Env Proxy
        --------------------------------
w/o SSL |     /    |    /   |             
w   SSL |     /    |   HN   |   HN         




#!/usr/bin/perl

require LWP::UserAgent;
my $ua = LWP::UserAgent->new;
my $useproxy = 0;
my $useenviroment = 0;
my $usessl = 0;

if($useproxy) {
	my $httpproxy = "localhost:8080";
	my $proxyserver = "";
	if($usessl) {
		if($useenviroment) {
			$ENV{HTTPS_PROXY} = "https://".$httpproxy;
			$ua->env_proxy();
		}
		else {
			$proxyserver = "https://".$httpproxy;
			$ua->proxy(['http', 'https'], $proxyserver);
		}
	}
	else {
		$proxyserver = "http://".$httpproxy;
		$ua->proxy(['http', 'https'], $proxyserver);
	}
}

my $target = "https://server-you-can-tail-logs-for.com";
my $response = $ua->get($target);
print $response->status_line;


tested using:
perl v5.10.1 under cygwin
activestate perl

```

**Comment by tomrittervg** [comment]
Oh, my ticket was migrated! Neat. Might as well subscribe. Now if only I remember what the heck problem this caused...

**Comment by oalders** [comment]
This is one old ticket! We've been trying to chip away at these. This one predates my involvement by quite a few years. To be honest, I didn't even know there was anything left in the RT queue until earlier today. But since there's some code to reproduce the issue, maybe we can clear this one up?

**Comment by afresh1** [comment]
This appears to be [the `$fullpath` from LWP::Protocol::https](https://github.com/libwww-perl/libwww-perl/blob/d9621c61cc5bd7f275a501f7b7b5d7d9cf87662d/lib/LWP/Protocol/http.pm#L154-L167) and it appears that's what it is supposed to do if using a proxy without an `$ssl_tunnel` (line 162).   I've never written a proxy server, so I don't know whether that's correct or not.  However [wikipedia says](https://en.wikipedia.org/wiki/Proxy_server#Web_proxy_servers):
> The request from the client is the same as a regular HTTP request except the full URL is passed, instead of just the path.[[17](https://en.wikipedia.org/wiki/Proxy_server#cite_note-rfc7230.5.3.2-17)]

IMO this sounds like a bug in burp proxy, but I can't find a bugtracker or changelog for it, so no idea if it was reported or fixed.

(I'm trying to find an actual bug to fix for my pullrequest.club assignment for this month, but it's not going terribly well)

**Comment by oalders** [comment]
Thanks @afresh1. I think we can close this one as well. You're doing great work. ;)
