### ISSUE TITLE
environment case-insensitive warning painful

### ISSUE THREAD

**Issue by kberry** [libwww-perl/libwww-perl#372]
As of LWP::UserAgent 6.52, and perhaps somewhat earlier, it started to complain about case-insensitive "clashes" of environment variables when env_proxy was set. Even for environment variables that have nothing to do with LWP, and even when the environment is case sensitive (e.g., Unix :). This is frustrating, since it newly requires "cleaning" things which, it seems to me, LWP should not be complaining about. For example, say we have the trivial tryua.pl:
```
use LWP; my $ua = LWP::UserAgent->new( env_proxy => 1 );
```
and then run
```
env foo=1 FOO=2 perl tryua.pl
```
There is output:
```
Environment contains multiple differing definitions for 'foo'.                  
Using value from 'FOO' (2) and ignoring 'foo' (1) at /usr/local/lib/perl5/site_\
perl/5.32.1/LWP/UserAgent.pm line 1117.        
```

(Naturally, in practice the issue is not with explicitly-specified envvars like this, but case-varying envvars that I have set in my environment for reasons unrelated to LWP.)

At least for me, tt would be nice if either LWP wouldn't complain on case-sensitive systems, or wouldn't complain about envvars that it doesn't ever read, or at least had an option to suppress these checks. Thanks for considering.

**Comment by oalders** [comment]
That sounds like some unintended side effects of https://github.com/libwww-perl/libwww-perl/pull/355

Those changes are specifically made to clear up any ambiguity around having both `http_proxy` and `HTTP_PROXY` env vars set, so switching off the checks where the env vars are case sensitive would defeat part of that change set.

I think we need to restrict this check to env vars that we care about it and not warn in other cases. Pull request certainly welcome. :)

**Comment by kberry** [comment]
I'll append a simple diff for your consideration, essentially duplicating the "we don't care about this envvar" tests from the bottom of the loop. I can't easily generate a PR, sorry. Also, the logic of that for loop is not exactly clear to me (sorry again), so I expect you'll want to adjust the change in some wa or another. Please consider this contribution trivial/uncopyrightable/public domain/do as you like :). Thanks for considering.

```
--- ORIG/UserAgent.pm   2021-01-07 22:21:10.000000000 +0100
+++ UserAgent.pm        2021-02-22 23:52:37.864725750 +0100
@@ -1114,2 +1114,6 @@
         if (my $from_key= $seen{$k}) {
+            # Do not complain about envvars that we never look at.
+            next unless $k =~ /^(.*)_proxy$/;
+            next unless $k =~ /^$URI::scheme_re\z/;
+            next unless LWP::Protocol::implementor($k);
             warn "Environment contains multiple differing definitions for '$k'.\n".
```

**Comment by oalders** [comment]
Thanks @kberry!

**Comment by BipulMl10** [comment]
Hi,  Did you get the chance to check the above.
