### ISSUE TITLE
Overly noisy warnings about Content-Length when not even set

### ISSUE THREAD

**Issue by PaulGWebster** [libwww-perl/libwww-perl#373]
It is very noisy to see messages such as :

> Content-Length header value was wrong, fixed at /usr/local/lib/perl5/site_perl/5.30.3/LWP/Protocol/http.pm line 264.

fly down during an initialization when content-length was never even set (I presumed LWP would calculate this its self, which it did but raises the above warning about it), it should not raise this warning when no content-length has been set what so ever.

**Comment by oalders** [comment]
Thanks @PaulGWebster. Do you have a snippet to demonstrate the problem?

**Comment by PaulGWebster** [comment]
> Thanks @PaulGWebster. Do you have a snippet to demonstrate the problem?

This will not 'just work' as it refers to an enclosed docker stack however I am sure you can modify it to point to a local server that accepts post:

```               
                my $request = POST($req_url);
                $request->header('Accept' => 'application/json');
                $request->header('Content-Type' => 'application/json');
                $request->content(encode_json($create_ehr_body_clone));

                my $ua = LWP::UserAgent->new();
                my $res = $ua->request($request);
```

**Comment by oalders** [comment]
```perl
use strict;
use warnings;

use Cpanel::JSON::XS qw( encode_json );
use HTTP::Request::Common qw( POST );
use LWP::UserAgent ();

my $foo = { bar => 'baz' };

my $request = POST('https://www.example.com');
$request->header( 'Accept'       => 'application/json' );
$request->header( 'Content-Type' => 'application/json' );
$request->content( encode_json($foo) );

my $ua  = LWP::UserAgent->new();
my $res = $ua->request($request);
```

```
Content-Length header value was wrong, fixed at /Users/olafalders/.plenv/versions/5.30.3/lib/perl5/site_perl/5.30.3/LWP/Protocol/http.pm line 264.
```

**Comment by karenetheridge** [comment]
Content-Length is being set to 0 in the POST() call because no content is provided.  If content is later added, the appropriate headers must be corrected.

The more correct way to construct the request in your code would be:

```
my $request = POST('https://www.example.com',                                                      
  'Accept'       => 'application/json',
  'Content-Type' => 'application/json',                                                             
  Content => encode_json($foo),                                                                     
);
```
