### ISSUE TITLE
Upgrading LWP past version 6.46 fails with HTTP::Daemon 6.00 installed, works with 6.12.

### ISSUE THREAD

**Issue by fitzmorrispr** [libwww-perl/libwww-perl#374]
With HTTP::Daemon version 6, I would repeatedly get the following test failures when having cpan attempt an `upgrade LWP` or `install OALDERS/libwww-perl-6.47.tar.gz`,
```
#   Failed test 'request had cookie header'
#   at t/local/http.t line 426.
# GET /echo HTTP/1.1
# Connection: TE, close
# Authorization: Digest username="user2", realm="libwww-perl-digest", qop=auth, algorithm="MD5", uri="/echo", nonce="12345", nc=00000008, cnonce="603d7108", response="112cdaf9f6b079aef13c66f7219cb4e5"
# From: gisle@aas.no
# Host: localhost:45593
# TE: deflate,gzip;q=0.3
# User-Agent: Mozilla/0.01 libwww-perl/6.52
#

#   Failed test 'request had only one cookie header'
#   at t/local/http.t line 430.
#          got: '0'
#     expected: '1'
# Looks like you failed 2 tests of 130.
```

this was despite `t/00-report-prereqs.t` reporting 
```
# === Runtime Requires ===
#
#     Module                Want    Have
#     --------------------- ---- -------
#     [...]
#     HTTP::Cookies            6    6.00
#     HTTP::Daemon             6    6.00
````

I diffed the http.t files for version 6.46 and 6.47, and saw that the cookie tests, and their requirement for HTTP::Cookies were the only change, so I tried an `upgrade HTTP::Cookies` which installed 6.10, but had the same test failures.

Then, because I noticed that the file also used `HTTP::Daemon`, I did an `upgrade HTTP::Daemon` which installed version 6.12*. As soon as I did, `upgrade LWP` worked flawlessly. So it's pretty clear that 6.00 is not a high enough version, or at least, isn't on this system. It might be worth mentioning that the upgrade for `HTTP::Daemon` did skip some tests, saying `Can't talk to ourself (misconfigured system)` (something I don't have the privileges to fix)

*This also pulled in Module::Build::Tiny, which itself pulled in ExtUtils::Config, ::Helpers, and ::InstallPaths, but none of these were listed by report_prereqs.
(I already had ExtUtils::MakeMaker 7.10_02 and Module::Metadata 1.000031 which was all that report_prereqs seemed to want)

**Comment by oalders** [comment]
Thanks for reporting @fitzmorrispr!

**Comment by ppisar** [comment]
Upgrading HTTP::Daemon from 6 to 6.12 is too strong. The reported t/local/http.t failure disappears when upgrading HTTP-Deamon from 6.00 to 6.01. HTTP-Daemon's changelog reads:

~~~~
2012-02-18 HTTP-Daemon 6.01

If you bind localhost, don't trust gethostbyaddr() to resolve the
address.  [RT#67247]
~~~~

I recommend lowering the minimal version to 6.01.

**Comment by oalders** [comment]
I will defer to @skaji  on this.
