### ISSUE TITLE
nodename nor servname provided - LWP::UserAgent not closing sockets correctly?

### ISSUE THREAD

**Issue by DrHyde** [libwww-perl/libwww-perl#379]
I'm running this on Mac OS Catalina (Intel), in case that matters.

I'm getting the error `Can't connect to cpan.metacpan.org:443 (nodename nor servname provided, or not known)` from LWP::UserAgent when I use it from within CPAN::FindDependencies. That module figures out all of a distribution's dependencies by downloading META.* files (or tarballs when the meta-file isn't available) from metacpan. For some distributions that can be a _lot_ of requests.

You can see my code [here](https://github.com/DrHyde/perl-modules-CPAN-FindDependencies/blob/debuggery-for-LWP-UserAgent/lib/CPAN/FindDependencies.pm#L281-L296) with some extra debuggery to show what it's trying to fetch and what it's getting back. As you can see it's not doing anything fancy. The only slightly unusual thing is the call to `env_proxy` which is there in case any of my code's users have `http_proxy` and friends set, but it is not set in my environment so should have no effect.

From my git checkout (NB the branch name in the link above):

```
$ perl -Ilib bin/cpandeps Acme::Mom::Yours perl 5.32.1 2>&1|less
1  _get https://cpan.metacpan.org/modules/02packages.details.txt.gz succeeded
2  _get https://cpan.metacpan.org/authors/id/A/AD/ADAMK/Acme-Mom-Yours-0.02.meta succeeded
3  _get https://cpan.metacpan.org/authors/id/G/GR/GRM/App-CamelPKI-0.07.meta failed: <html>
<head><title>404 Not Found</title></head> ...
4  _get https://cpan.metacpan.org/authors/id/G/GR/GRM/CamelPKI/App-CamelPKI-0.07.tar.gz succeeded
5  _get https://cpan.metacpan.org/authors/id/D/DW/DWHEELER/App-Info-0.57.meta succeeded
6  _get https://cpan.metacpan.org/authors/id/L/LE/LEONT/Module-Build-0.4231.meta succeeded
```

The 404 in that is fine. It continues in the same vein until ...

```
252  _get https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/HTML-Lint-2.32.meta succeeded
253  _get https://cpan.metacpan.org/authors/id/A/AL/ALEXMV/String-BufferStack-1.16.meta succeeded
254  _get https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/JSON-XS-4.03.meta failed: Can't connect to cpan.metacpan.org:443 (nodename nor servname provided, or not known)
```

From that point on every single request fails with the same error. I don't believe this is a real DNS problem, nor is it due to throttling, because if I run two jobs like that in parallel they both fail at the same point as above. I *think* that the error message is misleading. 253 successful connections, plus STDOUT, plus STDIN, plus STDERR == 256, and ...

```
$ ulimit -a|grep 256
open files                      (-n) 256
```

I wonder if perhaps LWP::UserAgent isn't properly closing sockets?

And if that is the problem, then once it's fixed an upstream bug report will need to be created to see if IO::Socket::INET can be made to give a more helpful error :-)

**Comment by karenetheridge** [comment]
Are Net::SSLeay and LWP::Protocol::https fully up to date?

**Comment by DrHyde** [comment]
Yes. I've also tried using the same `$ua` object throughout and keep_alive, with no luck.

**Comment by eserte** [comment]
I can reproduce the descriptor leakage on a linux system like this (used shell is zsh):
```
$ (limit descriptors 30; cpandeps Acme::Mom::Yours --perl 5.30.3)
Can't write /tmp/CPAN-FindDependencies-se3n3vuY: Too many open files
```
But as you see, the error message is different. And looking into the process with `lsof` shows that temporary files are accumulated:
```
...
cpandeps 505686 slaven_rezic    3u   REG   259,2     1168 21500651 /tmp/CPAN-FindDependencies-GeUD9_NG
cpandeps 505686 slaven_rezic    4u   REG   259,2   204141 21500652 /tmp/CPAN-FindDependencies-FHgXbDPW
cpandeps 505686 slaven_rezic    5u   REG   259,2     1974 21500653 /tmp/CPAN-FindDependencies-EUfEtvwm
cpandeps 505686 slaven_rezic    6u   REG   259,2     4968 21500654 /tmp/CPAN-FindDependencies-7MsWMpZI
cpandeps 505686 slaven_rezic    7u   REG   259,2     6073 21500655 /tmp/CPAN-FindDependencies-kA54rwYn
cpandeps 505686 slaven_rezic    8u   REG   259,2     1351 21500656 /tmp/CPAN-FindDependencies-E5ygLTfn
cpandeps 505686 slaven_rezic    9u   REG   259,2    19684 21500657 /tmp/CPAN-FindDependencies-g4XrqMJk
...
```
