### ISSUE TITLE
Can't call method "header" on unblessed reference.

### ISSUE THREAD

**Issue by davewood** [libwww-perl/libwww-perl#381]
Can't call method "header" on unblessed reference at /home/epplication/EPPlication/local/lib/perl5/LWP/UserAgent.pm line 118.

https://github.com/libwww-perl/libwww-perl/blob/master/lib/LWP/UserAgent.pm#L118

dgoing to take a while to extract a minimal example. let me know if you need it.

**Comment by oalders** [comment]
Are you passing in a `default_headers` argument somewhere that is not an `HTTP::Headers` object?

https://metacpan.org/pod/LWP::UserAgent#default_headers

**Comment by davewood** [comment]
precisely, im moving from HTTP::Tiny yo LWP::UserAgent and missed that I have to change the default_headers value.

thank you!
