### ISSUE TITLE
Mirror ignores utime errors silently

### ISSUE THREAD

**Issue by scop** [libwww-perl/libwww-perl#395]
`LWP::UserAgent::mirror` silently ignores possible `utime()` errors:

https://github.com/libwww-perl/libwww-perl/blob/fe2c323a46fd13332a1f790546c8784716644ba0/lib/LWP/UserAgent.pm#L1044

Should the user docs be updated to note this is the case (and a code comment be added it's intentional), or should it cause a warning, or should it `die`? I think one of these should be done ;)

**Comment by oalders** [comment]
I know we don't like to add new warnings, but it seems like a warning would be in order here.

**Comment by karenetheridge** [comment]
I agree. I can already hear the sysadmins screaming about new warnings showing up in logs, but it's a *legitimate* warning.

**Comment by scop** [comment]
#399 has first cut implementation.

`lwp-download` is similarly affected, should we patch it too? It isn't documented to sync the modification time and for it doing that is not as essential as for mirror here.

**Comment by oalders** [comment]
I think it would make sense to patch `lwp-download` as well. 👍
