### ISSUE TITLE
mirror should preserve existing file's modes and ownership

### ISSUE THREAD

**Issue by scop** [libwww-perl/libwww-perl#396]
mirror should preserve an existing file's modes and ownership. Currently they get set to the defaults in effect.

wget and curl do this. Haven't looked at how they implement preserving the ownerships -- can see how it can be done in non-atomic way, but that wouldn't be too nice.

Modes on the other hand are not a problem. But arguably preserving mode but not ownership (if it's a problem, see above) isn't good enough.

**Comment by oalders** [comment]
Closed via #393
