### ISSUE TITLE
LWP::UserAgent not returning the object of HTTP::Response 

### ISSUE THREAD

**Issue by gauravthethinker** [libwww-perl/libwww-perl#403]
I am using LWP::UserAgent version 5.833 in which when I am trying to get the status of http request I am not getting that .

use LWP::UserAgent;
my $ua = LWP::UserAgent->new( );
$ua->timeout(30);
my $req = HTTP::Request->new(POST => "$EndPoint");
$req->content_type('text/xml');
$req->content($send_data);
my $response = $ua->request($req);

If I am running the below code I am getting error Can't locate object method "is_success" via package "HTTP/1.1 200 OK

if ($response->is_success) {
    print $response->decoded_content;
}
else {
    die $response->status_line;
}

When I am doing a print on $response I get this 

HTTP/1.1 200 OK
Connection: close
Date: Mon, 10 Jan 2022 16:42:51 GMT
Accept: text/xml, text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Server: Apache
Vary: Accept-Encoding
Content-Length: 318
Content-Type: text/xml;charset=utf-8
Client-Date: Mon, 10 Jan 2022 16:42:51 GMT
Client-Peer: XXXXXX
Client-Response-Num: 1
SOAPAction: ""

**Comment by ikegami** [comment]
The code doesn't run, much less give the output you claim. Please post the code you actually ran.

**Comment by petdance** [comment]
Also, if `$response` is not an HTTP::Response object, then what is it?

**Comment by gauravthethinker** [comment]
> 

HTTP/1.1 200 OK
Connection: close
Date: Mon, 10 Jan 2022 16:42:51 GMT
Accept: text/xml, text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Server: Apache
Vary: Accept-Encoding
Content-Length: 318
Content-Type: text/xml;charset=utf-8
Client-Date: Mon, 10 Jan 2022 16:42:51 GMT
Client-Peer: 10.80.40.19:80
Client-Response-Num: 1
SOAPAction: ""
