### ISSUE TITLE
Could we improve error with Module::Load?

### ISSUE THREAD

**Issue by michal-josef-spacek** [libwww-perl/libwww-perl#429]
When I don't present Module::Load in the system, there is an error with bad loading of cookie_jar_class. This is confusing.
Problematic code in LWP::UserAgent:
```
...
        my $class = $self->{cookie_jar_class};
        try {
            require Module::Load;
            Module::Load::load($class);
            $jar = $class->new(%$jar);
        }
        catch {
            my $error = $_;
            if ($error =~ /Can't locate/) {
                die "cookie_jar_class '$class' not found\n";
            }
            else {
                die "$error\n";
            }
        };
...
```

**Comment by michal-josef-spacek** [comment]
I am packaging this module in Fedora, so in each change I am going through code changes. And I tested build without this dependencies. And result was confusing.

In reality you could lose module and error without name of missing module isn't what you want :-)
This is minor thing, but I think that's better to fix.

**Comment by oalders** [comment]
Thank you for packaging this module. ❤️

**Comment by haarg** [comment]
Module::Load should probably just be converted to a use line at the top of the module.
