### ISSUE TITLE
LWP::UserAgent throws error with version 6.69 and above

### ISSUE THREAD

**Issue by cthotadi** [libwww-perl/libwww-perl#432]
Hi,

I am using the following snippet

```perl
use strict;
use warnings;
use LWP::UserAgent;
use LWP::ConnCache;

my $userAgent = LWP::UserAgent->new(conn_cache => 1);
$userAgent->conn_cache(LWP::ConnCache->new());
$userAgent->conn_cache->total_capacity(10);
$userAgent->timeout(15);
```
I am seeing the following error when using libwww-perl version >= 6.69
![image](https://github.com/libwww-perl/libwww-perl/assets/32841391/ce0f2606-4bd2-49e7-91f8-e48057f00d90)

The above snippet is working fine with version 6.68 though. Can anyone let me know If I need to change something here to make it work?

**Comment by haarg** [comment]
`1` was never a valid value for `conn_cache`, it just previously wouldn't be accessed until later.

You could change your code to either:
```
my $userAgent = LWP::UserAgent->new;
$userAgent->conn_cache(LWP::ConnCache->new());
$userAgent->conn_cache->total_capacity(10);
$userAgent->timeout(15);
```
or
```
my $userAgent = LWP::UserAgent->new(conn_cache => {});
$userAgent->conn_cache->total_capacity(10);
$userAgent->timeout(15);
```
