### ISSUE TITLE
noproxy partial matches with leading dot no longer works

### ISSUE THREAD

**Issue by defc0n** [libwww-perl/libwww-perl#433]
In #426 it broke the ability to set a `noproxy` value of `.example.com` and have it match `www.example.com`. Note that tools such as `curl` support doing that (although apparently tools such as `wget` do not). It is very likely this will break things for others that relied upon that previous behavior.

It does make sense that `ample.com` should not match `www.example.com` (as well as `.ample.com`).

**Comment by oalders** [comment]
@defc0n do you have a proposed fix?

**Comment by defc0n** [comment]
> @defc0n do you have a proposed fix?

I do not; I was working on a unit test but didn't get that far, sorry.

**Comment by oalders** [comment]
Closed via #447
