### ISSUE TITLE
LWP https connect and https proxy issue

### ISSUE THREAD

**Issue by cyrillpetroff** [libwww-perl/libwww-perl#434]
Hello. Do I understand correctly that the current implementation of libwwwperl does not support https connections through https proxies? Because of the IO::Socket::SSL module?
I get an error like `fatal SSL error: SSL connect attempt failed error:140940CD:SSL routines:ssl3_read_bytes:invalid alert`

**Comment by oalders** [comment]
I think we'd probably need some working code in order to replicate this. Do you have an example of what you're trying to do?

**Comment by cyrillpetroff** [comment]
The problem is in the IO::Socket::SSL module, I left a bug report and it confirmed it.

**Comment by oalders** [comment]
Thanks, @cyrillpetroff! I will close this for now and we can re-open again if that's needed.
