### ISSUE TITLE
$ENV{PERL_LWP_SSL_VERIFY_HOSTNAME} = 0 seems to be ignored on new install, EL-9 (and osx),  OpenSSL 3+, Perl-5.26+

### ISSUE THREAD

**Issue by rshingleton** [libwww-perl/libwww-perl#448]
I just did an install on 2 machines, a RHEL-9 host and a MAC M2. Installed using cpm to latest versions available. Previously working code on a host with self signed certificates:

---snippet---
```
'# disable host checking for self-signed certs
$ENV{PERL_LWP_SSL_VERIFY_HOSTNAME} = 0;

my $url = "https://$host/api/storage/volumes";
my $ua = LWP::UserAgent->new(timeout => $timeout);
my $client = REST::Client->new(useragent => $ua);
$client->GET($url);
```

On previous install using OpenSSL 1.1.1 and LWP 6.67 I get the expected response where SSL verification is disabled. The two new installations seem to ignore the ENV var.

```
$VAR1 = '{"error":"Can\'t connect to selfsignedcerhost.dev.my.org:443 (certificate verify failed)\\n\\nSSL connect attempt failed error:0A000086:SSL routines::certificate verify failed at /prod/dependencies/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/5.26.3/LWP/Protocol/http.pm line 50.\\n"}';
```

I tried installing lower versions of LWP::UserAgent and some of the underlying packages with the same results. I had installed Perl-5.36.3 and tried backporting to 5.26.3 (as shown above) to match the working installs to no avail.

After poking around in the source and looking in the dependencies I was able to get it to work by setting
```
    $ua->ssl_opts(SSL_verify_mode => IO::Socket::SSL::SSL_VERIFY_NONE);
```

This behavior has seemingly changed somewhere and I'm uncertain as to what has caused it to behave differently. The most biggest change was going from OpenSSL 1.1.1 to OpenSSL 3x. I'm not sure how this affected the UserAgent but I've tried rolling back to earlier versions of LWP and several of its dependencies such as IO::Socket::SSL to match the version on my existing, working installations.vpan

------
#### Non-working install (also tested on Perl-5.36.3)

OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)
LWP::UserAgent
-------------------------------------------------------------------------
        (no description)
        O/OA/OALDERS/libwww-perl-6.72.tar.gz
        /prod/dependencies/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/5.26.3/LWP/UserAgent.pm
        Installed: 6.72
        CPAN:      6.72  up to date
        Olaf Alders (OALDERS)
        olaf@wundersolutions.com

#### Working install

OpenSSL 1.1.1k  FIPS 25 Mar 2021
LWP::UserAgent
-------------------------------------------------------------------------
	(no description)
	O/OA/OALDERS/libwww-perl-6.72.tar.gz
	/prod/dependencies/perl5/perlbrew/perls/perl-5.34.0/lib/site_perl/5.34.0/LWP/UserAgent.pm
	Installed: 6.67
	CPAN:      6.72  Not up to date
	Olaf Alders (OALDERS)
	olaf@wundersolutions.com

**Comment by oalders** [comment]
Maybe @noxxi has thoughts on this?

**Comment by noxxi** [comment]
The relevant code base is not LWP but LWP::Protocol::https, which is an external module. With version 6.11 the way it verifies certificates was harmonized to behave in sync with IO::Socket::SSL, i.e. use  root CA as detected by IO::Socket::SSL instead of doing it a different way, use options from IO::Socket::SSL instead of offering a different and in parts strange way. These changes were already for years in various distributions even before they were officially included in LWP::Protocol::https.

For more please the current documentation of LWP::Protocol::https, which no longer shows a PERL_LWP_SSL_VERIFY_HOSTNAME variable but documents the alternative way to disable certificate validation.

Please note also that it is not a good idea to disable certificate validation when faced with self-signed certificates, since this basically accepts arbitrary self-signed certificates, not only the intended ones. Instead just trust the specific certificate by using SSL_fingerprint option as documented in IO::Socket::SSL.

**Comment by haarg** [comment]
The disagreement here seems to be over the name. While the name has `VERIFY_HOSTNAME`, it has always disabled all certificate checks, not just hostname verification. That is how it was (and still is) documented to behave, and what the errors would indicate.

I don't think we should have accepted that patch, and I think debian was wrong to be using it.

**Comment by stigtsp** [comment]
> ... Instead just trust the specific certificate by using SSL_fingerprint option as documented in IO::Socket::SSL.

An alternative approach can be to download the self signed certs from the https server and providing it via the `SSL_CERT_FILE` env variable:

```sh
$ openssl s_client -showcerts -servername example.com -connect example.com:443 < /dev/null > ./self-signed.crt

$ SSL_CERT_FILE=./self-signed.crt perl -MLWP::UserAgent -E 'say LWP::UserAgent->new->get("https://example.com/")->decoded_content;'
```

This has the benefit of not requiring code changes

**Comment by oalders** [comment]
Ok to close this @rshingleton?

**Comment by rshingleton** [comment]
I'm OK with my solution, I can get around these issues. I have servers in a
secure environment where I can use "non-recommended" loopholes like this
and have most things centralized in an OOP fashion where I can
make targeted updates like this. I was more concerned that this was a
potentially breaking change for people who are less inclined to have this
type of encapsulation or capacity to troubleshoot like I did. If people
have this spread around in "legacy" code it could be a show stopper.

**Comment by oalders** [comment]
Do you think the docs could do a better job with this?

**Comment by rshingleton** [comment]
I think it's confusing from a historical standpoint. 

The first place I looked, and I would assume anyone encountering this would look is the [LWP::UserAgent](https://metacpan.org/pod/LWP::UserAgent) page. In the section for [ssl_opts](https://metacpan.org/pod/LWP::UserAgent#ssl_opts) there's a reference to the env var PERL_LWP_SSL_VERIFY_HOSTNAME which also has references all around the internet for disabling this check. Regardless if it's an affectation of LWP::Protocol::https, an external module, the functionality of LWP::UserAgent has changed, in what I would consider a braking way, from what has been in use for, I assume, years. 

I might suggest updating the docs or referencing these changes in some fashion so people will understand that just setting this env var is no longer enough to get around the checks and that the $ua->ssl_opts(SSL_verify_mode => IO::Socket::SSL::SSL_VERIFY_NONE) needs to be explicitly set.

**Comment by oalders** [comment]
> I might suggest updating the docs or referencing these changes in some fashion so people will understand that just setting this env var is no longer enough to get around the checks and that the $ua->ssl_opts(SSL_verify_mode => IO::Socket::SSL::SSL_VERIFY_NONE) needs to be explicitly set.

Thanks! If you have the bandwidth to submit a PR, I'm happy to look a it.

**Comment by rshingleton** [comment]
Finally got around to adding a paragraph for this: https://github.com/libwww-perl/libwww-perl/pull/457

Let me know if you need me to modify anything.
