### ISSUE TITLE
Issue with LWP::UserAgent, https IPv6 endpoint through proxy (using CONNECT): 400: Bad request

### ISSUE THREAD

**Issue by justnoxx** [libwww-perl/libwww-perl#449]
Dear libwww-perl team!

Recently we faced an issue with reaching our backend by ipv6 address (https proto) through http proxy.

Our code looks like the following:
```perl
use strict;
use warnings;
use Data::Dumper;
use LWP::UserAgent;

my $ssl_tunnel3 = '[fd00:0:1:1f::4]:8443/commanderRequest';
my $proxy = 'http://localhost:6800';

my $ua = LWP::UserAgent->new();
$ua->proxy(['http', 'https'], $proxy);
my $req = HTTP::Request->new(
	'POST',
    "https://$ssl_tunnel2"
);


my $resp = $ua->request(
    $req
);

print Dumper $resp;
```

Returns 400: bad request.

After some investigation it turned out that `LWP::Protocol::http` in `request` function creates `$host:$port` pair using concatenation through `:`, they are:

https://github.com/libwww-perl/libwww-perl/blob/master/lib/LWP/Protocol/http.pm#L155
```perl
my $ssl_tunnel = $proxy && $url->scheme eq 'https'
	&& $url->host.":".$url->port;
```

https://github.com/libwww-perl/libwww-perl/blob/master/lib/LWP/Protocol/http.pm#L161
```perl
my $fullpath =
	$method eq 'CONNECT' ? $url->host . ":" . $url->port :
	$proxy && ! $ssl_tunnel ? $url->as_string :
	do {
	    my $path = $url->path_query;
	    $path = "/$path" if $path !~m{^/};
	    $path
	};
```

In this code the `$url` variable is an object of `URI::*` class. As per documentation of URI (https://metacpan.org/pod/URI#$uri-%3Ehost(-$new_host-) ) the following statement is present:
> For IPv6 addresses the brackets around the raw address is removed in the return value from $uri->host. When setting the host attribute to an IPv6 address you can use a raw address or one enclosed in brackets. The address needs to be enclosed in brackets if you want to pass in a new port value as well.

So when our ipv6 address, the `[fd00:0:1:1f::4]:8443` comes into one of previous code it is being parsed into `URI` object and then concatenated back to `fd00:0:1:1f::4:8443`. Which is incorrect, so we are getting error at `LWP::Protocol::http`, L201: https://github.com/libwww-perl/libwww-perl/blob/master/lib/LWP/Protocol/http.pm#L201

However, the `host:port` concatenation could be replaced with `host_port` function (https://metacpan.org/pod/URI#$uri-%3Ehost_port(-$new_host_port-) ), see the description:
>For IPv6 addresses the bracketing is preserved; thus URI->new("http://[::1]/")->host_port returns "[::1]:80". Contrast this with $uri->host which will remove the brackets.

We did this change and now we at the following issue on the line 208: https://github.com/libwww-perl/libwww-perl/blob/master/lib/LWP/Protocol/http.pm#L208 (SSL Debug enabled by `use IO::Socket::SSL debug3`:

```
bash-5.1# ls /opt/cbflow/perl/lib/site_perl/5.32.1/LWP/Protocol/http.pm^C
(failed reverse-i-search)`cb-per': md5 /opt/^Cflow/perl/lib/site_perl/5.32.1/LWP/Protocol/http.pm
bash-5.1# cb-perl /tmp/cc.pl 
------
CONNECT [fd00:0:1:1f::4]:8443 HTTP/1.1
TE: deflate,gzip;q=0.3
Connection: TE, close
Host: [fd00:0:1:1f::4]:8443


------
DEBUG: .../IO/Socket/SSL.pm:3013: new ctx 28422848
DEBUG: .../IO/Socket/SSL.pm:1613: start handshake
DEBUG: .../IO/Socket/SSL.pm:730: ssl handshake not started
DEBUG: .../IO/Socket/SSL.pm:774: using SNI with hostname fd00:0:1:1f::4
DEBUG: .../IO/Socket/SSL.pm:815: request OCSP stapling
DEBUG: .../IO/Socket/SSL.pm:831: set socket to non-blocking to enforce timeout=180
DEBUG: .../IO/Socket/SSL.pm:845: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:3690: * TLSv1.3 (OUT), TLS handshake, Client hello (1)
DEBUG: .../IO/Socket/SSL.pm:848: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:858: ssl handshake in progress
DEBUG: .../IO/Socket/SSL.pm:868: waiting for fd to become ready: SSL wants a read first
DEBUG: .../IO/Socket/SSL.pm:888: socket ready, retrying connect
DEBUG: .../IO/Socket/SSL.pm:845: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:3690: * TLSv1.3 (IN), TLS alert, illegal parameter (559)
DEBUG: .../IO/Socket/SSL.pm:848: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:851: SSL connect attempt failed

DEBUG: .../IO/Socket/SSL.pm:851: local error: SSL connect attempt failed error:0A000417:SSL routines::sslv3 alert illegal parameter
DEBUG: .../IO/Socket/SSL.pm:854: fatal SSL error: SSL connect attempt failed error:0A000417:SSL routines::sslv3 alert illegal parameter
DEBUG: .../IO/Socket/SSL.pm:2037: downgrading SSL only, not closing socket
DEBUG: .../IO/Socket/SSL.pm:3062: free ctx 28422848 open=
DEBUG: .../IO/Socket/SSL.pm:3066: free ctx 28422848 callback
DEBUG: .../IO/Socket/SSL.pm:3073: OK free ctx 28422848
SCRIPT: 500 : SSL upgrade failed: SSL connect attempt failed error:0A000417:SSL routines::sslv3 alert illegal parameter at /opt/cbflow/perl/lib/site_perl/5.32.1/LWP/Protocol/http.pm line 208.
```

Can someone please help us to nail it down? Unfortunately, I am not an expert in `LWP::UserAgent` and `IO::Socket::SSL` interaction.

We are running inside of ipv6 docker, with the following system info:

perl -V:
```
perl -V
Summary of my perl5 (revision 5 version 32 subversion 1) configuration:
   
  Platform:
    osname=linux
    osvers=2.6.32-754.35.1.el6.x86_64
    archname=x86_64-linux
    uname='linux toolschain-lin1 2.6.32-754.35.1.el6.x86_64 #1 smp wed sep 16 06:48:01 edt 2020 x86_64 x86_64 x86_64 gnulinux '
    config_args='-d -e -Dcc=gcc -Duserelocatableinc -Dprefix=/opt/ec-toolchain/out/x86_64_Linux/perl-5.32.1 -Dccflags=-fno-stack-protector -Dlibpth= -Dlibs=-ldl -lm -lutil -lpthread -lc'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags ='-fno-stack-protector -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fno-stack-protector -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='10.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/opt/ec-toolchain/out/x86_64_Linux/gcc-10.4.0/lib/gcc/x86_64-pc-linux-gnu/10.4.0/include-fixed /usr/local/tools/x86_64_Linux/sysroot-glibc-2.12-1.212.el6/usr/lib /usr/local/lib /usr/local/tools/x86_64_Linux/sysroot-glibc-2.12-1.212.el6/usr/lib/../lib64 /lib /usr/lib /lib64 /usr/lib64 /usr/local/lib64
    libs=-ldl -lm -lutil -lpthread -lc
    perllibs=-ldl -lm -lutil -lpthread -lc
    libc=/usr/local/tools/x86_64_Linux/sysroot-glibc-2.12-1.212.el6/usr/lib/../lib64/libc.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.12'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Sep  7 2023 07:46:57
  @INC:
    /opt/cbflow/perl/lib/5.32.1/x86_64-linux
    /opt/cbflow/perl/lib/5.32.1
    /opt/cbflow/perl/lib
    /opt/cbflow/perl/lib/site_perl/5.32.1/x86_64-linux
    /opt/cbflow/perl/lib/site_perl/5.32.1
    /opt/cbflow/perl/lib/site_perl
    /opt/cbflow/perl/lib/site_perl/5.32.1/x86_64-linux
    /opt/cbflow/perl/lib/site_perl/5.32.1
    /opt/cbflow/perl/lib/5.32.1/x86_64-linux
    /opt/cbflow/perl/lib/5.32.1
```

LWP::UserAgent vesion: 6.73
IO::Socket::SSL version: 2.083
OpenSSL version: OpenSSL 3.0.12 24 Oct 2023 (Library: OpenSSL 3.0.12 24 Oct 2023)
Please let me know what else could I provide to help as much as possible.

Thanks and really appreciate your help!

**Comment by justnoxx** [comment]
> > LWP::UserAgent vesion: 6.53
> 
> Is this a typo? The latest version is 6.73

@oalders Yes, sorry, my fault, it is a typo, we have the latest LWP::UserAgent, we used both, from CPAN package and from master branch of this repo.

**Comment by oalders** [comment]
Thanks @justnoxx, since the current error is coming via `IO::Socket::SSL` I'd like to ping @noxxi for thoughts on this.

**Comment by oalders** [comment]
@justnoxx that's a good find. I would be great if you could make a PR for it.

**Comment by justnoxx** [comment]
@oalders I'll do it immediately after we get some confirmation from IO::Socket::SSL maintainer. Maybe this was done for a reason. Thanks.

**Comment by oalders** [comment]
Thanks, @noxxi!

@justnoxx would you be able to test out the proposed change and send a PR for that as well?

**Comment by justnoxx** [comment]
@oalders yes, will get back to you with changes soon

**Comment by justnoxx** [comment]
@oalders this is the first part: https://github.com/libwww-perl/libwww-perl/pull/450 Now I am going to create the pull request on LWP::Protocol::https.

**Comment by justnoxx** [comment]
@oalders the pull request for LWP::Protocol::https is also added https://github.com/libwww-perl/LWP-Protocol-https/pull/74/files

I've tested both, it works for me.

**Comment by oalders** [comment]
Thanks @justnoxx and @noxxi! New versions have been released. We can re-open this ticket if it turns out that something still needs to be changed.

**Comment by digint** [comment]
It turns out that something still needs to be changed, please re-open this ticket

This introduces a regression due to a bug in: 6e9101b

I have created a pull request fixing this issue:
https://github.com/libwww-perl/LWP-Protocol-https/pull/77

Note that without a `SSL_hostname` in `start_SSL`, openssl fails in the certificate validation. In order to make sure the change in 6e9101b is correct, we should make sure that certificate negotiation still works for certificates containing IP-addresses in the SAN (Subject Alternative Names), which is a widespread practice. I have not checked if there is some framework for this in the tests, I guess not.

@justnoxx did you have something specific in mind using `host_port` instead of `host`, or was that just by mistake?

**Comment by justnoxx** [comment]
@digint yes, it was critical for us since `host_port()` returns IPv6 addresses with brackets, while host does not. And when the IPv6 address is concatenated in `LWP::Protocol::http` using `host() . ':' . port()` it leads to wrong IPv6 address. I believe the good explanation of this issue is provided in the first comment. However, I am ready to help with solving this issue ASAP since we are very interested in the solution.

Cheers.

**Comment by justnoxx** [comment]
Also, @digint applying your patch will automatically make this issue relevant again so it won't work for IPv6 addresses anymore.
