### ISSUE TITLE
mirror() does not respect use_eval

### ISSUE THREAD

**Issue by ghost** [libwww-perl/libwww-perl#45]
With the use_eval option enabled LWP::UserAgent occasionally dies with the following error from mirror():

```
read timeout at /home/perl5/lib/site_perl/5.16.2/Net/HTTP/Methods.pm line 236. at /home/perl5/lib/site_perl/5.16.3/LWP/UserAgent.pm line 915.
```

I would expect this to not die and to be a response error instead, since the documentation for mirror says `The return value is the the response object.`

**Comment by genio** [comment]
I'll close this out for now under the assumption that some of the recent changes we made in wrapping things in eval{} would catch such errors. If I'm wrong, please re-open with sample code.
