### ISSUE TITLE
PATCH method not implemented for CLI

### ISSUE THREAD

**Issue by javierpuche** [libwww-perl/libwww-perl#451]
Many Linux distros include lwp-request by defautt and the aliases /usr/bin/POST and /usr/bin/GET for use in the command-line.
These commands are quite useful for testing purposes, including REST APIs, etc. 
POST supports PUT and DELETE methods with the -m option , but not PATCH, it is a pity, it wouild be great for completeness.

Sorry if this is not the place to ask for it.
Thanks in any case for your great and useful software.

**Comment by oalders** [comment]
Thanks, @javierpuche. If you're motivated to provide a pull request for this, I'd be happy to review it.

**Comment by oalders** [comment]
Closed via #452
