### ISSUE TITLE
Indirect dependency on Clone -> non-reporting to CPANtesters

### ISSUE THREAD

**Issue by jkeenan** [libwww-perl/libwww-perl#465]
This CPAN library is listed on metacpan as having a dependencies on CPAN distributions which, in turn, have a dependency on the Clone distribution.  That distribution is currently [FAILing on CPANtesters](http://www.cpantesters.org/cpan/report/c70621be-5c96-11ef-b179-cb1a840b22fd) due to a change in Perl 5 blead: the elimination of `'` from package and variable names.  That problem has been corrected in https://github.com/garu/Clone/issues/43 but a new CPAN release has not yet been issued.  Until such a new Clone release appears, distributions which depend on Clone will not be reached in dependency-order ("CPAN River") automated testing.  Such distributions will be classified `DISCARD`, *e.g.,*:
```
test DISCARD libwww-perl-6.77 (perl-5.41.3) x86_64-linux 6.1.0-18-amd64
```
... and we will not be able to assess whether they are adversely affected by other changes in Perl 5 blead.

**Comment by karenetheridge** [comment]
A new version of Clone has now been uploaded.
