### ISSUE TITLE
http request with https_proxy are handled with CONNECT on port  443

### ISSUE THREAD

**Issue by dod38fr** [libwww-perl/libwww-perl#57]
Hello

On Debian/sid with libwww-perl  6.07-1, I've a setup with proxy for both http and https:

```
$ env|grep proxy
http_proxy=http://localhost:8888
https_proxy=http://localhost:8888
```

The following GET command:

```
 GET 'http://qa.debian.org/cgi-bin/madison.cgi?package=perl&text=on'
```

fails with

```
SSL upgrade failed: SSL connect attempt failed with unknown error error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed at /usr/share/perl5/LWP/Protocol/http.pm line 193.
```

Tinyproxy logs shows:

```
CONNECT   Jul 09 19:25:57 [2317]: Connect (file descriptor 6): localhost [127.0.0.1]
CONNECT   Jul 09 19:25:57 [2317]: Request (file descriptor 6): GET http://qa.debian.org/cgi-bin/madison.cgi?package=perl&text=on HTTP/1.1
CONNECT   Jul 09 19:25:57 [2317]: Established connection to host "qa.debian.org" using file descriptor 7.
CONNECT   Jul 09 19:25:57 [23678]: Connect (file descriptor 6): localhost [127.0.0.1]
CONNECT   Jul 09 19:25:57 [23678]: Request (file descriptor 6): CONNECT qa.debian.org:443 HTTP/1.1
CONNECT   Jul 09 19:25:57 [23678]: Established connection to host "qa.debian.org" using file descriptor 7.
ERROR     Jul 09 19:25:57 [23678]: readbuff: recv() error "Connection reset by peer" on file descriptor 6
```

Looks like LWP attemps to setup a SSL connection through the proxy even though a plain http request was made. A CONNECT request is made on port 443 with is refused by Debian server. Shouldn't lwp send a plain http get to the proxy ?

If `https_proxy` variable is unset, the GET command works fine:

```
$ unset https_proxy
$  GET 'http://qa.debian.org/cgi-bin/madison.cgi?package=perl&text=on'
 perl | 5.10.1-17squeeze6 | squeeze-security | source, amd64, armel, i386, ia64, kfreebsd-amd64, kfreebsd-i386, mips, mipsel, powerpc, s390, sparc
 perl | 5.10.1-17squeeze6 | squeeze          | source, amd64, armel, i386, ia64, kfreebsd-amd64, kfreebsd-i386, mips, mipsel, powerpc, s390, sparc
```

tinyproxy shows:

```
CONNECT   Jul 09 19:27:03 [2316]: Connect (file descriptor 6): localhost [127.0.0.1]
CONNECT   Jul 09 19:27:03 [2316]: Request (file descriptor 6): GET http://qa.debian.org/cgi-bin/madison.cgi?package=perl&text=on HTTP/1.1
CONNECT   Jul 09 19:27:03 [2316]: Established connection to host "qa.debian.org" using file descriptor 7.
```

@noxxi: what do you think about this ?

**Comment by droidxna** [comment]
my $ua = LWP::UserAgent->new(ssl_opts => { SSL_hostname => '', SSL_verifycn_name => '' , SSL_verify_mode => 0x00, verify_hostname => 0 });

**Comment by guolin302** [comment]
INFO      Jul 19 11:56:08 [105549]: Closed connection between local client (fd:6) and remote client (fd:7)
CONNECT   Jul 19 11:56:18 [89420]: Connect (file descriptor 6): 10.10.61.251 [10.10.61.251]
CONNECT   Jul 19 11:56:18 [89420]: Request (file descriptor 6): CONNECT www.baidu.com:443 HTTP/1.1
INFO      Jul 19 11:56:18 [89420]: No upstream proxy for www.baidu.com
CONNECT   Jul 19 11:56:29 [89420]: Established connection to host "www.baidu.com" using file descriptor 7.
INFO      Jul 19 11:56:29 [89420]: Not sending client headers to remote machine
ERROR     Jul 19 11:56:29 [89420]: readbuff: recv() error "Connection reset by peer" on file descriptor 6

**Comment by genio** [comment]
https://github.com/libwww-perl/LWP-Protocol-https/pull/17 was merged and I'm assuming this can now be closed.  Please yell if I'm mistaken.
