### ISSUE TITLE
Remove LWP::Protocol::GHTTP

### ISSUE THREAD

**Issue by njtaylor** [libwww-perl/libwww-perl#80]
HTTP::GHTTP this hasn't been updated since 2002, and uses libghttp from an old version of gnome, newer gnome versions have replaced libghttp with libsoup.

LWP::Protocol::GHTTP could be removed.

There are no tests to check this works.

**Comment by genio** [comment]
An attempt at a separate module for LWP::Protocol::GHTTP has been created here https://github.com/genio/lwp-protocol-ghttp  If the idea of separating it this way isn't popular, the tests for it here: https://github.com/genio/lwp-protocol-ghttp/blob/master/t/00-load.t could be introduced into libwww-perl

**Comment by genio** [comment]
The separate dist has been shipped so that a version of LWP::Protocol::GHTTP is out there and available to those who may still be using it.  So, step one of removing it from this dist has been completed.

**Comment by genio** [comment]
GHTTP has been removed from this dist and will be gone in the next release!  Thanks everyone
