### ISSUE TITLE
LWP::UserAgent does not check Content-Length header

### ISSUE THREAD

**Issue by skaji** [libwww-perl/libwww-perl#86]
Even if Content-Length header is not equal to the actual content length,
LWP::UserAgent::request() returns a 200 OK response.

Here is an example:

``` perl
# test.pl
use strict;
use warnings;
use LWP::UserAgent;
use Plack::Loader;
use Test::TCP;

my $server = Test::TCP->new(code => sub {
    my $port = shift;
    my $app = sub {
        my $content = "hello world\n";
        [
            200,
            ['Content-Length' => 10000], # bigger than acutual content length
            [$content],
        ];
    };
    Plack::Loader->load('Standalone', port => $port)->run($app);
});

my $url = "http://localhost:" . $server->port;
my $http = LWP::UserAgent->new;
my $res = $http->get($url);
warn $res->status_line, "\n";
```

```
> perl test.pl
200 OK
```

As an end-user, I want LWP::UserAgent to check Content-Length header and if it is not equal to the actual content length, I want LWP::UserAgent to return a response which indicates failure.

**Comment by damog** [comment]
Can you please refer to the HTTP spec section where the client needs to err given the mismatch on body length and header?

**Comment by cavac** [comment]
A wrong content length interferes with connection reuse an may be a potential security problem.

For example, a server script may generate a content that also includes headers+body. By manipulating the content length header to make the number smaller (which the server shouldn't allow anyway), the server script may hijack the next client request over the same TCP connection by providing fake headers plus a potentially malicious content.

**Comment by FGasper** [comment]
Confirmed still happening in 6.24.

**Comment by genio** [comment]
We've looked into this several ways now. We also see the same behavior with Mojo. There doesn't appear to be a clean way to fix it. Every simple approach leaves things a bit sketchy and in some ways, outright broken. @skaji you mind taking a stab at it?

**Comment by oalders** [comment]
@skaji just wondering why this was closed?

**Comment by skaji** [comment]
I closed all issues and pull requests created by me that I am not currently intending to address.

If you think this issue should be left open, please feel free to reopen it.
