### ISSUE TITLE
Broken cpan/cpanm work, after install libwww-perl-6.15

### ISSUE THREAD

**Issue by mongoostic** [libwww-perl/libwww-perl#99]
Hi!
I'am using Debian 7 Whezzy, perlbrew, and on it perl -v 5.16.3.
Under perlbrew, I'am install cpanm, across cpanm App::cpanminus,
and cpanm work fine, I'am install more 200 modules, until I install module XML::Simple.
In dependicies from XML::Simple, also has been installed LWP::UserAgent,
and from this moment, I have this message from cpanm:

> skyton@debian-wheezy-base:/www$ cpanm XML::Simple
> --> Working on XML::Simple
> Fetching http://www.cpan.org/authors/id/G/GR/GRANTM/XML-Simple-2.22.tar.gz ... OK
> Configuring XML-Simple-2.22 ... OK
> ==> Found dependencies: XML::SAX::Expat
> --> Working on XML::SAX::Expat
> Fetching http://www.cpan.org/authors/id/B/BJ/BJOERN/XML-SAX-Expat-0.51.tar.gz ... ERROR: read failed: connection reset by remote peer at /home/skyton/perl5/perlbrew/perls/perl-5.16.3/lib
> /site_perl/5.16.3/LWP/Protocol/http.pm line 465. at /home/skyton/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/LWP/UserAgent.pm line 916.
> FAIL
> ! Download http://www.cpan.org/authors/id/B/BJ/BJOERN/XML-SAX-Expat-0.51.tar.gz failed. Retrying ...
> Configuring XML-SAX-Expat-0.51 ... OK
> ==> Found dependencies: XML::Parser
> --> Working on XML::Parser
> Fetching http://www.cpan.org/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz ... ERROR: read failed: connection reset by remote peer at /home/skyton/perl5/perlbrew/perls/perl-5.16.3/lib/sit
> e_perl/5.16.3/LWP/Protocol/http.pm line 465. at /home/skyton/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/LWP/UserAgent.pm line 916.
> FAIL
> ! Download http://www.cpan.org/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz failed. Retrying ...

and so on.
Now at install any module across cpan/cpanm, I have this error.
Help me please!
Thanks in advance!

p.s.
my machine is the virtual box guest. with nat. But cpanm work fine, until I try install XML::Simple.

**Comment by genio** [comment]
Hi, @mongoostic 

This seems to me, at a first glance, to be a connectivity problem. ```connection reset by remote peer``` is the server hanging up on you. Can you use ```tcpdump``` or something on your attempt to grab the files with LWP?  Are you making use of a proxy?

```lwp-download http://www.cpan.org/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz```

We'd be happy to discuss this with you on [IRC](https://chat.mibbit.com/?channel=%23lwp&server=irc.perl.org)

**Comment by genio** [comment]
@mongoostic 

I'm going to close this for now as I can't replicate your problem and believe it to be something related to your box's configuration.  I'll be happy to be wrong about my assumptions here, so please don't hesitate to speak up if you feel I'm overlooking the issue.

You might find it easier to communicate with us and get a faster result via [IRC](https://chat.mibbit.com/?channel=%23lwp&server=irc.perl.org). We'll be happy to help you look into it further from there. Keep in mind that a discussion there with us might very well prove me wrong and we can always reopen the issue to track it here if it is indeed an issue with LWP.

Thanks,
Chase
